maintainer=Snaipe <franklinmathieu@gmail.com>

name=libcsptr
version=2.0.2
source=https://github.com/Snaipe/$(name)/archive/v$(version).tar.gz
license=MIT
description=A smart pointers library for the (GNU) C programming language
homepage=http://github.com/Snaipe/libcsptr
category=libs

targets=deb rpm
archs=x86 amd64
kinds=bin dev doc

bin_files=usr/lib

include ../fpm.make
